name: bms_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  image_picker: ^1.2.0
  package_info_plus: ^8.3.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  uuid: ^4.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

  # Very Good Analysis
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
