// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1ja7jz1PNhOabRYRkkYT57gCFfLbWso',
    appId: '1:125570224857:web:05f0f436461d63da4564c8',
    messagingSenderId: '125570224857',
    projectId: 'bms-mobile-internal',
    authDomain: 'bms-mobile-internal.firebaseapp.com',
    storageBucket: 'bms-mobile-internal.firebasestorage.app',
    measurementId: 'G-07XE79E68Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdN8n0UsFdjZBeOMHmDToMMxIz3yuZXSg',
    appId: '1:125570224857:android:f066aebc1483831e4564c8',
    messagingSenderId: '125570224857',
    projectId: 'bms-mobile-internal',
    storageBucket: 'bms-mobile-internal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHBk11OVYXrnIFytMDVHI2PEncb35RwAY',
    appId: '1:125570224857:ios:dc29cf2b79ed515f4564c8',
    messagingSenderId: '125570224857',
    projectId: 'bms-mobile-internal',
    storageBucket: 'bms-mobile-internal.firebasestorage.app',
    iosBundleId: 'bmwmobileinternal.bmsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHBk11OVYXrnIFytMDVHI2PEncb35RwAY',
    appId: '1:125570224857:ios:dc29cf2b79ed515f4564c8',
    messagingSenderId: '125570224857',
    projectId: 'bms-mobile-internal',
    storageBucket: 'bms-mobile-internal.firebasestorage.app',
    iosBundleId: 'bmwmobileinternal.bmsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1ja7jz1PNhOabRYRkkYT57gCFfLbWso',
    appId: '1:125570224857:web:5f8386e16775bc8b4564c8',
    messagingSenderId: '125570224857',
    projectId: 'bms-mobile-internal',
    authDomain: 'bms-mobile-internal.firebaseapp.com',
    storageBucket: 'bms-mobile-internal.firebasestorage.app',
    measurementId: 'G-ZK8EN7FKHK',
  );
}
